/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_5;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca el primer número: ");
        int pnum = miScan.nextInt();
        
        System.out.println("Introduzca el segundo número: ");
        int snum = miScan.nextInt();
        
        System.out.println("Introduzca el tercer número: ");
        int tnum = miScan.nextInt();
        
    }
}
