/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_5;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        int grande;
        int mediano;
        int pequeño;

        
        System.out.println("Introduzca el primer número: ");
        int pnum = miScan.nextInt();
        
        System.out.println("Introduzca el segundo número: ");
        int snum = miScan.nextInt();
        
        System.out.println("Introduzca el tercer número: ");
        int tnum = miScan.nextInt();
        
        if (pnum >= snum){
            if(pnum >= tnum){
                grande = pnum;
                if(snum >= tnum){
                    mediano = snum;
                    pequeño = tnum;
                }
                else{ //tnum > snum
                    mediano = tnum;
                    pequeño = snum;
                }
            }
            else{ //tnum > pnum
                grande = tnum;
                mediano = pnum;
                pequeño = snum;
            }
        }else{ //snum > pnum
            if(pnum >= tnum){
                grande = snum;
                mediano = pnum;
                pequeño = tnum;
            }
            else{ //tnum > pnum
                if(snum >= tnum){
                    grande = snum;
                    mediano = tnum;
                    pequeño = pnum;
                }
                else{ //tnum > snum
                    grande = tnum;
                    mediano = snum;
                    pequeño = pnum;
                }
            }
        }
        System.out.println(grande + " > " + mediano + " > " + pequeño);
    }
}
